<x-layout>
    <table>
        <thead>
            <tr>
                <th>
                    Número
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    2
                </td>
            </tr>
        </tbody>
    </table>
</x-layout>
